# Generated by Django 5.2.10 on 2026-01-23 14:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_id', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_upstairs', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['-event_participations__event__date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='game_type_name_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='api.gametype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acronym', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('definition', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            options={
                'verbose_name': 'Glossary Entry',
                'verbose_name_plural': 'Glossary Entries',
                'ordering': ['acronym'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('acronym', ''), _negated=True), name='acronym_not_blank'), models.CheckConstraint(condition=models.Q(('definition', ''), _negated=True), name='definition_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='member_name_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='Quizmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='quizmaster_name_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.game')),
                ('quizmaster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.quizmaster')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Round number')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Round name')),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 7)), name='round_number_1_to_7'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='round_name_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='TeamEventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.SmallIntegerField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_participations', to='api.event')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_participations', to='api.table')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='api.team')),
            ],
            options={
                'ordering': ['-event__date', '-score'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('acquired_seating', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to='api.member')),
                ('team_event_participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_attendances', to='api.teameventparticipation')),
            ],
            options={
                'ordering': ['team_event_participation__event__date', 'member__name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(1)])),
                ('guest', models.BooleanField(editable=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='api.team')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='teameventparticipation',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='api.teamname'),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='theme_name_not_blank')],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='api.theme'),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='venue_name_not_blank')],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='api.venue'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vote', models.CharField(choices=[('R', 'Right'), ('W', 'Wrong'), ('A', 'Abstained')], default='A', max_length=1)),
                ('is_double_or_nothing', models.BooleanField(default=False, verbose_name='Double or nothing vote')),
                ('member_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.memberattendance')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.round')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='memberattendance',
            constraint=models.UniqueConstraint(fields=('member', 'team_event_participation'), name='unique_member_team_event_participation_attendance'),
        ),
        migrations.AddConstraint(
            model_name='teamname',
            constraint=models.UniqueConstraint(fields=('name', 'team'), name='unique_team_name'),
        ),
        migrations.AddConstraint(
            model_name='teamname',
            constraint=models.UniqueConstraint(condition=models.Q(('guest', True)), fields=('name',), name='unique_guest_team_name'),
        ),
        migrations.AddConstraint(
            model_name='teamname',
            constraint=models.UniqueConstraint(condition=models.Q(('guest', True)), fields=('team',), name='guest_team_single_name'),
        ),
        migrations.AddConstraint(
            model_name='teamname',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='team_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='teameventparticipation',
            constraint=models.UniqueConstraint(fields=('team', 'event'), name='unique_team_event_participation'),
        ),
        migrations.AddConstraint(
            model_name='teameventparticipation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('score__gte', -1), ('score__lte', 112)), ('score__isnull', True), _connector='OR'), name='valid_score'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('game', 'date'), name='unique_game_date_event'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(condition=models.Q(('day__isnull', False)), fields=('game_type', 'day', 'time', 'venue'), name='unique_official_game'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(condition=models.Q(('day__isnull', True)), fields=('game_type', 'venue'), name='unique_unofficial_game'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('day__isnull', True), models.Q(('day__gte', 0), ('day__lte', 6)), _connector='OR'), name='day_range_0_to_6'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('day__isnull', True), ('time__isnull', True)), models.Q(('day__isnull', False), ('time__isnull', False)), _connector='OR'), name='day_time_both_null_or_notnull'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('member_attendance', 'round'), name='unique_vote'),
        ),
    ]
