# Generated by Django 5.2.10 on 2026-01-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberattendance',
            options={'ordering': ['-team_event_participation__event__date', 'member__name']},
        ),
    ]
