# Generated by Django 5.2.10 on 2026-02-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_memberattendance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['venue__name', 'game_type__name', 'day', 'time']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.AddField(
            model_name='venue',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_id',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Table ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Team ID'),
        ),
    ]
