# Generated by Django 5.2.11 on 2026-03-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_game_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('venue__name', 'game_type__name', 'day', 'time')},
        ),
        migrations.AlterModelOptions(
            name='gametype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='glossary',
            options={'ordering': ('acronym',), 'verbose_name': 'Glossary Entry', 'verbose_name_plural': 'Glossary Entries'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='memberattendance',
            options={'ordering': ('-team_event_participation__event__date', 'member__name')},
        ),
        migrations.AlterModelOptions(
            name='quizmaster',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ('number',)},
        ),
        migrations.AlterModelOptions(
            name='teameventparticipation',
            options={'ordering': ('-event__date', '-score')},
        ),
        migrations.AlterModelOptions(
            name='teamname',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='memberattendance',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='Table ID'),
        ),
    ]
