# Generated by Django 6.0.3 on 2026-04-28 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_event_options_alter_game_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='join_code',
            field=models.CharField(blank=True, default='', max_length=6, validators=[django.core.validators.RegexValidator(message='Join code must be exactly 6 digits', regex='^\\d{6}$')]),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('join_code__regex', '^\\d{6}$'), ('join_code', ''), _connector='OR'), name='join_code_six_digits_or_blank'),
        ),
    ]
