# Generated by Django 6.0.4 on 2026-05-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_event_join_code_alter_event_quizmaster_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Round',
            new_name='RoundType',
        ),
    ]
