# Generated by Django 6.0.4 on 2026-05-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_round_roundtype'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_vote',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='round',
            new_name='round_type',
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('member_attendance', 'round_type'), name='unique_vote'),
        ),
    ]
