# Generated by Django 6.0.4 on 2026-05-08 00:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_vote_unique_vote_rename_round_vote_round_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, default='')),
                ('image', models.URLField(blank=True, default='')),
                ('answer_count', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, help_text='The number of answers required by the question', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Number of answers')),
                ('external_id', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ('-round__event__date', 'external_id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, default='', max_length=150)),
                ('instructions', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('-event__date', '-round_type__number'),
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='roundtype',
            options={'ordering': ('number', 'double_or_nothing')},
        ),
        migrations.RemoveConstraint(
            model_name='roundtype',
            name='round_number_1_to_7',
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.CharField(blank=True, default='', help_text='URL slug for the event, theoretically unique', max_length=24, validators=[django.core.validators.RegexValidator(message='Slug must be exactly 24 lowercase hex characters', regex='^[0-9a-f]{24}$')]),
        ),
        migrations.AddField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(blank=True, help_text='Client ID used in combination with the slug for live game polling', null=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='roundtype',
            name='double_or_nothing',
            field=models.BooleanField(default=True, help_text='Whether or not this round allows for double or nothing'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the event ended, generated by the autoscraper', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='join_code',
            field=models.CharField(blank=True, default='', help_text='User-facing 6-digit code used to join live games', max_length=6, validators=[django.core.validators.RegexValidator(message='Join code must be exactly 6 digits', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='roundtype',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Round name'),
        ),
        migrations.AlterField(
            model_name='roundtype',
            name='number',
            field=models.PositiveSmallIntegerField(help_text="The round's order number in the game, 1-indexed", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Round number'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '^[0-9a-f]{24}$'), ('slug', ''), _connector='OR'), name='slug_twenty_four_hex'),
        ),
        migrations.AddConstraint(
            model_name='roundtype',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 8)), name='round_number_1_to_8'),
        ),
        migrations.AddConstraint(
            model_name='roundtype',
            constraint=models.UniqueConstraint(fields=('number', 'double_or_nothing'), name='unique_round_number_double_or_nothing'),
        ),
        migrations.AddField(
            model_name='round',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='api.event'),
        ),
        migrations.AddField(
            model_name='round',
            name='round_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='api.roundtype'),
        ),
        migrations.AddField(
            model_name='question',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.round'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('event', 'round_type'), name='unique_event_round_type'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('text', ''), _negated=True), ('image', '')), models.Q(('text', ''), models.Q(('image', ''), _negated=True)), _connector='OR'), name='question_text_xor_image'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('answer_count__gte', 1), ('answer_count__lte', 10)), name='question_answer_count_range'),
        ),
    ]
