# Generated by Django 6.0.4 on 2026-05-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_question_round_alter_roundtype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='uuid',
        ),
    ]
