# Generated by Django 6.0.5 on 2026-06-06 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_event_uuid'),
        ('scraper', '0003_geocodedaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.geocodedaddress', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='TeamRoundSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('double_or_nothing', models.BooleanField(default=False, help_text='Whether or not the team chose to double for this round')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_submissions', to='api.round')),
                ('team_event_participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_submissions', to='api.teameventparticipation')),
            ],
            options={
                'ordering': ('-team_event_participation__event__date', '-round__round_type__number'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, default='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.question')),
                ('team_round_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.teamroundsubmission')),
            ],
            options={
                'ordering': ('-team_round_submission__team_event_participation__event__date', 'question__external_id'),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='teamroundsubmission',
            constraint=models.UniqueConstraint(fields=('team_event_participation', 'round'), name='unique_team_event_participation_round_submission'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('team_round_submission', 'question'), name='unique_team_round_submission_question_answer'),
        ),
    ]
