# Generated by Django 6.0.6 on 2026-06-06 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_venue_address_alter_venue_url_teamroundsubmission_and_more'),
        ('scraper', '0003_geocodedaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='scraper.geocodedaddress'),
        ),
    ]
