# Generated by Django 6.0.6 on 2026-06-14 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_venue_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-external_id',)},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ('external_id',)},
        ),
        migrations.AlterModelOptions(
            name='teamroundsubmission',
            options={'ordering': ('-team_event_participation__event__date', '-event_round__round__round_type__number')},
        ),
        migrations.RemoveConstraint(
            model_name='round',
            name='unique_event_round_type',
        ),
        migrations.RemoveConstraint(
            model_name='teamroundsubmission',
            name='unique_team_event_participation_round_submission',
        ),
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='external_id',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='External round ID'),
        ),
        migrations.AddField(
            model_name='eventround',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rounds', to='api.event'),
        ),
        migrations.AddField(
            model_name='eventround',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rounds', to='api.round'),
        ),
        migrations.AddField(
            model_name='teamroundsubmission',
            name='event_round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_submissions', to='api.eventround'),
        ),
        migrations.AddConstraint(
            model_name='teamroundsubmission',
            constraint=models.UniqueConstraint(fields=('team_event_participation', 'event_round'), name='unique_team_event_participation_round_submission'),
        ),
        migrations.RemoveField(
            model_name='round',
            name='event',
        ),
        migrations.RemoveField(
            model_name='teamroundsubmission',
            name='round',
        ),
        migrations.AddConstraint(
            model_name='eventround',
            constraint=models.UniqueConstraint(fields=('event', 'round'), name='unique_event_round'),
        ),
    ]
