# Generated by Django 6.0.6 on 2026-06-14 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_eventround_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='External round ID'),
        ),
        migrations.AlterField(
            model_name='teamroundsubmission',
            name='event_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_submissions', to='api.eventround'),
        ),
    ]
