# Generated by Django 6.0.6 on 2026-06-25 19:41

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_round_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametype',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[core.validators.validate_not_empty_string]),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[core.validators.validate_not_empty_string]),
        ),
        migrations.AlterField(
            model_name='quizmaster',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[core.validators.validate_not_empty_string]),
        ),
        migrations.AlterField(
            model_name='roundtype',
            name='name',
            field=models.CharField(max_length=100, validators=[core.validators.validate_not_empty_string], verbose_name='Round name'),
        ),
        migrations.AlterField(
            model_name='teamname',
            name='name',
            field=models.CharField(max_length=300, validators=[core.validators.validate_not_empty_string]),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[core.validators.validate_not_empty_string]),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[core.validators.validate_not_empty_string]),
        ),
    ]
