# Generated by Django 6.0.4 on 2026-05-18 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', help_text="Username. Can be blank, probably shouldn't be.", max_length=100)),
                ('email', models.EmailField(help_text='Must be routed to the email worker to receive login codes', max_length=254, unique=True)),
                ('token', models.CharField(blank=True, default='', help_text='JWT issued after login', max_length=1000)),
                ('player_id', models.CharField(blank=True, default='', help_text='Player ID (exactly 24 lowercase hexadecimal characters)', max_length=24, validators=[django.core.validators.RegexValidator(message='Player ID must be exactly 24 lowercase hex characters', regex='^[0-9a-f]{24}$')])),
            ],
            options={
                'ordering': ('email',),
                'constraints': [models.CheckConstraint(condition=models.Q(('player_id__regex', '^[0-9a-f]{24}$'), ('player_id', ''), _connector='OR'), name='player_id_twenty_four_hex')],
            },
        ),
    ]
