# Generated by Django 6.0.5 on 2026-05-23 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperaccount',
            name='player_id',
            field=models.CharField(blank=True, default='', help_text='Player ID (exactly 24 lowercase hexadecimal characters)', max_length=24, validators=[django.core.validators.RegexValidator(message='Player ID must be exactly 24 lowercase hex characters', regex='^[0-9a-f]{24}$')], verbose_name='Player ID'),
        ),
    ]
