# Generated by Django 6.0.5 on 2026-06-06 15:42

import core.validators
import django.core.validators
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_scraperaccount_player_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(help_text='The postal address that was geocoded', max_length=500, unique=True, validators=[core.validators.validate_not_empty_string])),
                ('timezone', timezone_field.fields.TimeZoneField(help_text='The timezone corresponding to the geocoded address', validators=[core.validators.validate_not_empty_string], verbose_name='Time Zone')),
                ('longitude', models.FloatField(help_text='The longitude of the geocoded address', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('latitude', models.FloatField(help_text='The latitude of the geocoded address', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
            ],
            options={
                'verbose_name_plural': 'geocoded addresses',
                'ordering': ('address',),
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('address', ''), _negated=True), name='address_not_empty'), models.CheckConstraint(condition=models.Q(('timezone', ''), _negated=True), name='timezone_not_empty'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='valid_longitude'), models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='valid_latitude')],
            },
        ),
    ]
