services:
  tunnel:
    image: cloudflare/cloudflared:latest
    depends_on:
      - frontend
    secrets:
      - dumbjared_cloudflared_token
    command: tunnel run
    environment:
      - TUNNEL_TOKEN_FILE=/run/secrets/dumbjared_cloudflared_token
      - TUNNEL_METRICS=localhost:60123
      - NO_AUTOUPDATE=true
    networks:
      - ingress
    healthcheck:
      test:
        [
          "CMD",
          "cloudflared",
          "tunnel",
          "--metrics",
          "localhost:60123",
          "ready",
        ]
      interval: 60s
      timeout: 5s
      start_period: 30s
      start_interval: 3s

  frontend:
    image: neutronlul/dumbjared-frontend:latest
    depends_on:
      - nginx
    networks:
      - internal
      - ingress
    healthcheck:
      interval: 60s
      start_interval: 5s

  nginx:
    image: nginxinc/nginx-unprivileged:latest
    depends_on:
      - backend
    volumes:
      - unixsocket:/run/sockets/:ro
      - static:/static/:ro
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
        uid: "101"
        gid: "101"
        mode: 0400
    networks:
      - internal
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 60s
      timeout: 5s
      start_period: 30s
      start_interval: 5s

  backend:
    image: neutronlul/dumbjared-backend:latest
    command:
      [
        "gunicorn",
        "config.wsgi",
        "--bind=unix:/app/socket/gunicorn.sock",
        "--workers=3",
      ]
    depends_on:
      - database
      - redis
      - playwright
    environment:
      - SECRET_KEY_FILE=/run/secrets/dumbjared_backend_key
      - POSTGRES_PASSWORD_FILE=/run/secrets/dumbjared_postgres_password
    volumes:
      - unixsocket:/app/socket/
      - static:/app/static/
    secrets:
      - dumbjared_backend_key
      - dumbjared_postgres_password
    networks:
      - backend
    healthcheck:
      interval: 60s
      start_interval: 5s

  database:
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/dumbjared_postgres_password
    secrets:
      - dumbjared_postgres_password
    networks:
      - backend
    healthcheck:
      interval: 60s
      start_interval: 5s

  redis:
    networks:
      - backend
    healthcheck:
      interval: 60s
      start_interval: 5s

  playwright:
    image: neutronlul/dumbjared-playwright:latest
    networks:
      - backend
    healthcheck:
      interval: 60s
      start_interval: 5s

  beat:
    image: neutronlul/dumbjared-backend:latest
    command: ["celery", "-A", "config", "beat", "--loglevel=info"]
    environment:
      - SECRET_KEY_FILE=/run/secrets/dumbjared_backend_key
      - POSTGRES_PASSWORD_FILE=/run/secrets/dumbjared_postgres_password
    depends_on:
      - backend
      - redis
      - database
    secrets:
      - dumbjared_backend_key
      - dumbjared_postgres_password
    networks:
      - backend
    healthcheck:
      interval: 60s
      start_interval: 5s

  worker:
    image: neutronlul/dumbjared-backend:latest
    command: [
        "celery",
        "-A",
        "config",
        "worker",
        "--autoscale=4,1", # Maybe scale down to 0?
        "--loglevel=info",
      ]
    environment:
      - SECRET_KEY_FILE=/run/secrets/dumbjared_backend_key
      - POSTGRES_PASSWORD_FILE=/run/secrets/dumbjared_postgres_password
    depends_on:
      - backend
      - redis
      - database
    secrets:
      - dumbjared_backend_key
      - dumbjared_postgres_password
    networks:
      - backend
    healthcheck:
      interval: 60s
      start_interval: 5s

volumes:
  postgres_data:
  unixsocket:
  static:

networks:
  ingress:
    driver: overlay
  internal:
    driver: overlay
  backend:
    driver: overlay

configs:
  nginx_config:
    file: ./nginx.conf

secrets:
  dumbjared_cloudflared_token:
    external: true
  dumbjared_backend_key:
    external: true
  dumbjared_postgres_password:
    external: true
