services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          initial_sync: true
        - action: rebuild
          path: ./frontend/package-lock.json
    healthcheck:
      interval: 30s
      start_interval: 1s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    depends_on:
      database:
        condition: service_healthy
      playwright:
        condition: service_healthy
    environment:
      - DEBUG=true
      - ALLOWED_HOSTS=backend,localhost
      - DJANGO_SUPERUSER_PASSWORD=admin
      - CACHE_BACKEND=django.core.cache.backends.locmem.LocMemCache
      - CACHE_LOCATION=
    ports:
      - "8000:8000"
    healthcheck:
      interval: 30s
      start_interval: 1s
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          initial_sync: true
          ignore:
            - entrypoint.*.sh
            - uv.lock
            - .python-version
        - action: rebuild
          path: ./backend/uv.lock

  database:
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      interval: 30s
      start_interval: 1s

  playwright:
    healthcheck:
      interval: 30s
      start_interval: 1s

  # pgui:
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@example.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     database:
  #       condition: service_healthy

  # chartdb:
  #   image: ghcr.io/chartdb/chartdb:latest
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - DISABLE_ANALYTICS=true

volumes:
  postgres_data:
