name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build images and run tests
        run: |
          mkdir -p coverage/reports && chmod 777 coverage/reports && \
          docker compose -f compose.test.yaml run --rm backend \
          pytest --cov-report=xml:/app/output/backend-coverage.xml \
          --junitxml=/app/output/junit.xml -o junit_family=legacy

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ !cancelled() }}
        with:
          fail_ci_if_error: true
          files: ./coverage/reports/backend-coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Upload test results to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ !cancelled() }}
        with:
          fail_ci_if_error: true
          files: ./coverage/reports/junit.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          report_type: test_results

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Ruff check
        uses: astral-sh/ruff-action@v3
        if: ${{ !cancelled() }}
        with:
          version-file: "./backend/pyproject.toml"
          src: "./backend"
          args: "check --output-format=github"

      - name: Ruff format
        uses: astral-sh/ruff-action@v3
        if: ${{ !cancelled() }}
        with:
          version-file: "./backend/pyproject.toml"
          src: "./backend"
          args: "format --check --diff --output-format=github"
